### ISSUE TITLE
Don't kill other tasks even when any task failed.

### ISSUE THREAD

**Issue by friend1ws** [otiai10/hotsub#101]
複数のタスクを実行していて、途中でどれかが異常終了した時の挙動として、
・とりあえず、その他のタスクはできるだけ処理を続ける（アップロードまで）
・しかし、最後にhotsubの全体としては異常終了コードを返す。
・（とりあえずは超簡易的で良いので）異常終了したタスクが同定可能な形にする。

が望ましいと考えます。

**Comment by otiai10** [comment]
When any of concurrent tasks failed,

- Any other tasks should continue running until getting completed (including `Push`)
- `hotsub` process should return `non-0` exit code as a whole
- Any of logs should tell which task failed
