### ISSUE TITLE
Protocol for executing awsub batch jobs on public data

### ISSUE THREAD

**Issue by friend1ws** [otiai10/hotsub#82]
I would like to prepare some well-defined protocols to execute awsub-determined batch jobs on publicly available data (such as TCGA, SRA), so that users who want to use awsub on this purpose can promptly start their task.

**Comment by otiai10** [comment]
c.f) https://academic.oup.com/bioinformatics/article/32/16/2551/1743271

**Comment by otiai10** [comment]
https://github.com/hotsub/lab/issues/6
